name: qr_attendance_frontend
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.10.1

dependencies:
    image_picker: ^1.0.7
    dropdown_button2: ^2.3.9
    flutter:
        sdk: flutter
    cupertino_icons: ^1.0.8

    # --- 1. Architecture & State Management (Clean Architecture) ---
    # Required for "Business Logic Layer: BLoC"
    flutter_bloc: ^9.1.1

    equatable: ^2.0.7 # Helps compare states in BLoC efficiently

    # --- 2. Hardware & Sensors (The "Meat" of the project) ---
    # Required for "Camera quét mã QR động"
    ai_barcode_scanner: ^7.1.0

    # Required for "Định vị GPS thực" & validation
    geolocator: ^14.0.2

    # Required to ask for Camera & Location permissions gracefully
    permission_handler: ^12.0.1

    # Required for "Ràng buộc thiết bị" (Check UUID/Model)
    device_info_plus: ^12.3.0

    # --- 3. Networking & Security ---
    # Required for "RESTful API" connection
    dio: ^5.9.0

    # Required for "Bảo mật" - storing tokens and device UUIDs safely
    flutter_secure_storage: ^10.0.0

    # Required for Real-time updates (optional but recommended for "Thông báo")
    socket_io_client: ^3.1.3

    # --- 4. UI & Visuals ---
    # Required for "Vẽ biểu đồ (Pie/Bar Chart)"
    fl_chart: ^1.1.1

    # Required for "Xem bảng công" (Calendar View)
    table_calendar: ^3.2.0

    # Helper for formatting dates (e.g., "dd/MM/yyyy") in logs/calendar
    intl: ^0.20.2

    # --- 5. Notifications ---
    firebase_messaging: ^16.1.0

    flutter_local_notifications: ^19.5.0

    firebase_core: ^4.3.0

    sqflite: ^2.4.2

    shared_preferences: ^2.5.4
    app_links: ^7.0.0
    file_picker: ^10.3.8
    connectivity_plus: ^7.0.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
